DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS alumnis CASCADE;
DROP TABLE IF EXISTS moderators CASCADE;
DROP TABLE IF EXISTS otp_transtactions CASCADE;
DROP TABLE IF EXISTS qr_code_transactions CASCADE;
DROP TABLE IF EXISTS usage_logs CASCADE;
DROP TABLE IF EXISTS users CASCADE;