DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS alumnis;
DROP TABLE IF EXISTS alumni_news;
DROP TABLE IF EXISTS moderators CASCADE;
DROP TABLE IF EXISTS otp_transactions CASCADE;
DROP TABLE IF EXISTS qr_code_transactions CASCADE;
DROP TABLE IF EXISTS usage_logs CASCADE;
DROP TABLE IF EXISTS users CASCADE;